import {createProject,closeRing,pointInPolygon,buildDxf,extractNetworkLinks,normalizeMrd128Unit,getMrd128Legend,kmlColorToCss} from './src/core.mjs';
import {shouldFollowSurficialLink} from './src/mrd128-cache.mjs';
const $=id=>document.getElementById(id), STORAGE='phase-i-esa-project-v2', MRD='./data/mrd128.kml';
let project=(()=>{for(const k of [STORAGE,'phase-i-esa-project-v1']){try{const v=localStorage.getItem(k);if(v)return JSON.parse(v)}catch{}}return createProject()})();
let active='A',draw=null,pts=[],siteMarker,siteLayer,buildingLayer,draft,geoLayer,printMoved=false;
const geo={surficial:[],bedrock:[]}, geoSource={surficial:null,bedrock:null};
const map=L.map('map').setView([43.75,-79.3],11), street=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,crossOrigin:true,attribution:'© OpenStreetMap contributors'}).addTo(map), sat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,crossOrigin:true,attribution:'Tiles © Esri'});
L.control.scale({imperial:false,maxWidth:160}).addTo(map);
const north=L.control({position:'topright'});north.onAdd=()=>{const e=L.DomUtil.create('div','north-arrow');e.innerHTML='<div class="north-n">N</div><div class="north-glyph">▲</div>';return e};north.addTo(map);
const legendControl=L.control({position:'bottomright'});legendControl.onAdd=()=>{const e=L.DomUtil.create('div','map-legend');e.id='mapLegend';return e};legendControl.addTo(map);
function save(){project.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE,JSON.stringify(project));$('saveState').textContent='Saved';setTimeout(()=>$('saveState').textContent='Local',700)}
function status(id,t,k=''){$(id).textContent=t;$(id).dataset.kind=k}
function sync(){for(const [id,k] of [['projectName','name'],['projectNo','projectNo'],['address','address'],['projectDate','date']])$(id).value=project[k]||'';$('dpi').value=project.dpi||300;$('dpiBadge').textContent=`${project.dpi||300} DPI`;if(project.location){map.setView([project.location.lat,project.location.lng],16);setMarker(project.location)};redraw();renderFigures();renderAerials();refreshPrint();updateLegend()}
for(const [id,k] of [['projectName','name'],['projectNo','projectNo'],['address','address'],['projectDate','date']])$(id).oninput=e=>{project[k]=e.target.value;save();refreshPrint()};$('dpi').onchange=e=>{project.dpi=+e.target.value;$('dpiBadge').textContent=`${project.dpi} DPI`;save()};
$('searchAddress').onclick=async()=>{const q=$('address').value.trim();if(!q)return;status('searchStatus','Searching…');try{const r=await fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(q)}`,{headers:{'Accept-Language':'en'}}),a=await r.json();if(!a.length)throw Error('Address not found');project.address=a[0].display_name;project.location={lat:+a[0].lat,lng:+a[0].lon};$('address').value=project.address;setMarker(project.location);map.setView([project.location.lat,project.location.lng],17);save();status('searchStatus',`Located: ${project.address}`,'ok');detect()}catch(e){status('searchStatus',`Search failed: ${e.message}`,'error')}};
function setMarker(p){siteMarker?.remove();const icon=L.divIcon({className:'',html:'<div class="site-marker"></div>',iconSize:[18,18],iconAnchor:[9,9]});siteMarker=L.marker([p.lat,p.lng],{icon,draggable:true}).addTo(map).bindTooltip('SITE',{permanent:true,direction:'top',offset:[0,-8]});siteMarker.on('dragend',()=>{const q=siteMarker.getLatLng();project.location={lat:q.lat,lng:q.lng};$('coords').textContent=`${q.lat.toFixed(6)}, ${q.lng.toFixed(6)}`;save();detect()});$('coords').textContent=`${p.lat.toFixed(6)}, ${p.lng.toFixed(6)}`}
function begin(m){draw=m;pts=[];draft?.remove();$('drawState').textContent=m==='site'?'Drawing site':'Drawing building';map.getContainer().style.cursor='crosshair'}
$('setSite').onclick=()=>{draw='marker';$('drawState').textContent='Tap site'};$('drawSite').onclick=()=>begin('site');$('drawBuilding').onclick=()=>begin('building');$('undoPoint').onclick=()=>{pts.pop();draft?.remove();if(pts.length)draft=L.polyline(pts.map(([x,y])=>[y,x]),{color:'#fbbf24',dashArray:'7 5'}).addTo(map)};$('clearGeometry').onclick=()=>{project.siteBoundary=[];project.buildingBoundary=[];redraw();save()};
map.on('click',e=>{if(!draw)return;if(draw==='marker'){project.location={lat:e.latlng.lat,lng:e.latlng.lng};setMarker(project.location);draw=null;save();detect();return}pts.push([e.latlng.lng,e.latlng.lat]);draft?.remove();draft=L.polyline(pts.map(([x,y])=>[y,x]),{color:'#fbbf24',dashArray:'7 5'}).addTo(map)});
$('finishDraw').onclick=()=>{if(!draw||draw==='marker'||pts.length<3){draw=null;$('drawState').textContent='Idle';return}const r=closeRing(pts);if(draw==='site')project.siteBoundary=r;else project.buildingBoundary=r;draw=null;pts=[];draft?.remove();draft=null;$('drawState').textContent='Idle';redraw();save()};
function redraw(){siteLayer?.remove();buildingLayer?.remove();if(project.siteBoundary?.length)siteLayer=L.polygon(project.siteBoundary.map(([x,y])=>[y,x]),{color:'#ef4444',weight:4,fill:false}).addTo(map);if(project.buildingBoundary?.length)buildingLayer=L.polygon(project.buildingBoundary.map(([x,y])=>[y,x]),{color:'#111827',weight:3,dashArray:'6 4',fillColor:'#fff',fillOpacity:.1}).addTo(map)}
function renderFigures(){const h=$('figureList');h.innerHTML='';for(const [c,f] of Object.entries(project.figures)){const d=document.createElement('div');d.className='figure-row'+(c===active?' active':'');d.innerHTML=`<div class="figure-top"><div><div class="figure-code">FIGURE ${c}</div><div class="figure-title">${f.title}</div></div><span class="badge">${fmt(f.extentMeters)}</span></div><div class="figure-actions"><button>View</button><button>Use for A3</button></div>`;d.children[1].children[0].onclick=()=>selectFig(c,true);d.children[1].children[1].onclick=()=>selectFig(c,false);h.appendChild(d)}}
function fmt(m){return m>=1000?`${m/1000} km`:`${m} m`}function selectFig(c,z){active=c;renderFigures();if(z)zoom(c);renderGeo();refreshPrint();if(c==='D'&&!geo.surficial.length&&project.location)loadMRD(false)}function zoom(c){if(!project.location)return;const r=Math.max(80,project.figures[c].extentMeters/2);map.fitBounds(L.circle([project.location.lat,project.location.lng],{radius:r}).getBounds(),{padding:[24,24],animate:false})}
for(const b of document.querySelectorAll('.basemap'))b.onclick=()=>{document.querySelectorAll('.basemap').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(b.dataset.map==='satellite'){map.removeLayer(street);sat.addTo(map)}else{map.removeLayer(sat);street.addTo(map)}};
$('uploadAerial').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const y=+$('aerialYear').value||new Date().getFullYear(),u=await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)});project.historical=project.historical||[];project.historical.push({id:crypto.randomUUID(),year:y,name:f.name,size:f.size,dataUrl:u});save();renderAerials();status('imageryStatus',`Added ${f.name} for ${y}`,'ok')};function renderAerials(){const a=project.historical||[];$('aerialCount').textContent=a.length;$('aerialList').innerHTML=a.length?a.map(x=>`<div class="aerial-item"><b>${x.year}</b> — ${esc(x.name)}</div>`).join(''):'No historical imagery added.'}$('openEarth').onclick=()=>project.location?window.open(`https://earth.google.com/web/@${project.location.lat},${project.location.lng},500a,1000d,35y,0h,0t,0r`,'_blank'):alert('Set the site location first.');
$('loadMrd128').onclick=()=>loadMRD(true);async function loadMRD(user=true){if(!project.location){if(user)alert('Locate the property first.');return}status('geologyStatus','Loading OGS MRD128…');try{const r=await fetch(MRD,{cache:'no-cache'}),t=await r.text();await loadDataset(t,'surficial','MRD128-REV (OGS)',new URL(MRD,location.href).href)}catch(e){status('geologyStatus',`MRD128 load failed: ${e.message}. Upload polygon KML/KMZ directly if the OGS server blocks browser access.`,'error')}}
$('uploadGeology').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{let t;if(f.name.toLowerCase().endsWith('.kmz')){const z=await JSZip.loadAsync(f),k=Object.values(z.files).find(x=>x.name.toLowerCase().endsWith('.kml'));if(!k)throw Error('No KML in KMZ');t=await k.async('text')}else t=await f.text();await loadDataset(t,$('geologyKind').value,f.name,null)}catch(x){status('geologyStatus',`Import failed: ${x.message}`,'error')}};
async function loadDataset(t,kind,name,base){let fs=parsePolys(t),docs=1;if(!fs.length&&base){const r=await resolveLinks(t,base,kind);fs=r.features;docs+=r.docs}if(!fs.length){const target=extractNetworkLinks(t).find(x=>/surficial geology$/i.test(x.name)||/\/polygons\/doc\.kml$/i.test(x.href));throw Error(`No polygon features resolved.${target?' Official polygon link: '+target.href:''}`)}geo[kind]=fs;geoSource[kind]=name;project.geology=project.geology||{};project.geology[kind]={name,count:fs.length,docs};save();renderGeo();detect();status('geologyStatus',`Loaded ${fs.length.toLocaleString()} ${kind} polygon(s) from ${name}`,'ok')}
async function resolveLinks(root,base,kind){const q=[{t:root,u:base,d:0}],seen=new Set([base]),out=[];let docs=0;while(q.length&&docs<30){const c=q.shift();for(const l of netLinks(c.t).filter(x=>follow(x,kind))){if(!relevant(l))continue;const u=normUrl(l.href,c.u);if(!u||seen.has(u))continue;seen.add(u);try{status('geologyStatus',`Loading MRD128 map section ${docs+1}…`);const t=await fetchKml(u);docs++;const p=parsePolys(t);out.push(...p);if(c.d<4&&!p.length)q.push({t,u,d:c.d+1})}catch(e){console.warn('KML link failed',u,e)}}}return{features:out,docs}}
function netLinks(t){const d=new DOMParser().parseFromString(t,'application/xml');return[...d.querySelectorAll('NetworkLink')].map(n=>{const b=n.querySelector('Region LatLonAltBox, LatLonAltBox'),num=x=>Number(b?.querySelector(x)?.textContent),bounds=b&&[num('north'),num('south'),num('east'),num('west')].every(Number.isFinite)?{north:num('north'),south:num('south'),east:num('east'),west:num('west')}:null;return{name:n.querySelector(':scope > name')?.textContent?.trim()||'',href:n.querySelector('Link href, Url href, href')?.textContent?.trim()||'',bounds}}).filter(x=>x.href)}
function follow(l,k){return k!=='surficial'||shouldFollowSurficialLink(l)}function relevant(l){if(!project.location||!l.bounds)return true;const p=project.location,b=l.bounds;return p.lat<=b.north&&p.lat>=b.south&&p.lng<=b.east&&p.lng>=b.west}function normUrl(h,b){try{const u=new URL(h,b);if(u.protocol==='http:'&&/geologyontario\./i.test(u.hostname))u.protocol='https:';return u.href}catch{return null}}async function fetchKml(u){const r=await fetch(u,{mode:'cors'});if(!r.ok)throw Error(`HTTP ${r.status}`);if(/\.kmz(?:\?|$)/i.test(u)){const z=await JSZip.loadAsync(await r.arrayBuffer()),k=Object.values(z.files).find(x=>x.name.toLowerCase().endsWith('.kml'));if(!k)throw Error('No KML in remote KMZ');return k.async('text')}return r.text()}
function parsePolys(t){const d=new DOMParser().parseFromString(t,'application/xml');if(d.querySelector('parsererror'))throw Error('Invalid KML/XML');const styles=new Map;for(const s of d.querySelectorAll('Style[id]')){const c=s.querySelector('PolyStyle color')?.textContent?.trim(),p=c?kmlColorToCss(c):null;if(p)styles.set(s.id,p)}for(const sm of d.querySelectorAll('StyleMap[id]')){const p=[...sm.querySelectorAll('Pair')].find(x=>x.querySelector('key')?.textContent?.trim()==='normal'),r=p?.querySelector('styleUrl')?.textContent?.trim().replace(/^#/,'');if(r&&styles.has(r))styles.set(sm.id,styles.get(r))}const out=[];for(const pm of d.querySelectorAll('Placemark')){const name=pm.querySelector(':scope > name')?.textContent?.trim()||'Geology unit',desc=strip(pm.querySelector(':scope > description')?.textContent||''),props={};for(const x of pm.querySelectorAll('ExtendedData Data'))props[x.getAttribute('name')||'']=x.querySelector('value')?.textContent?.trim()||'';for(const x of pm.querySelectorAll('ExtendedData SimpleData'))props[x.getAttribute('name')||'']=x.textContent?.trim()||'';const code=[name,...Object.values(props),desc].map(normalizeMrd128Unit).find(Boolean)||null,off=code?getMrd128Legend(code):null,su=pm.querySelector(':scope > styleUrl')?.textContent?.trim().replace(/^#/,'')||'',ic=pm.querySelector(':scope > Style PolyStyle color')?.textContent?.trim(),ks=ic?kmlColorToCss(ic):styles.get(su),color=ks?.color||off?.color||'#5fa8d3';for(const p of pm.querySelectorAll('Polygon')){const c=p.querySelector('outerBoundaryIs LinearRing coordinates');if(!c)continue;const a=c.textContent.trim().split(/\s+/).map(v=>v.split(',').slice(0,2).map(Number)).filter(v=>Number.isFinite(v[0])&&Number.isFinite(v[1]));if(a.length>=3)out.push({name:off?`${off.code.toUpperCase()} — ${off.title}`:name,description:off?off.detail:desc,unitCode:code,official:off,polygon:closeRing(a),color,fillOpacity:ks?.opacity??.42})}}return out}function strip(s){const e=document.createElement('div');e.innerHTML=s;return(e.textContent||'').replace(/\s+/g,' ').trim()}
function renderGeo(){geoLayer?.remove();geoLayer=null;const k=active==='D'?'surficial':active==='E'?'bedrock':null;if(!k){updateLegend();return}if(geo[k].length)geoLayer=L.layerGroup(geo[k].map(g=>L.polygon(g.polygon.map(([x,y])=>[y,x]),{color:'#334155',weight:1,fillColor:g.color,fillOpacity:g.fillOpacity}).bindPopup(`<b>${esc(g.name)}</b><br>${esc(g.description)}`))).addTo(map);updateLegend()}function detect(){const k=active==='E'?'bedrock':'surficial',a=geo[k];if(!project.location||!a.length){$('geoUnitBadge').textContent='—';$('geoLegend').textContent=a.length?'Set site location.':`No ${k} polygons loaded.`;updateLegend();return}const p=[project.location.lng,project.location.lat],h=a.find(g=>pointInPolygon(p,g.polygon));$('geoUnitBadge').textContent=h?.unitCode?.toUpperCase()||h?.name||'No hit';$('geoLegend').innerHTML=h?`<div class="legend-row"><span class="swatch" style="background:${h.color}"></span><div><b>${esc(h.name)}</b><br>${esc(h.description)}</div></div>`:'Site does not intersect a loaded polygon.';if(h){project.geology[k]={...(project.geology[k]||{}),siteUnit:h.unitCode||h.name,siteDescription:h.description};save()}updateLegend(h)}function updateLegend(force){const b=$('mapLegend'),k=active==='D'?'surficial':active==='E'?'bedrock':null;if(!k){b.style.display='none';return}b.style.display='block';let h=force;if(!h&&project.location)h=geo[k].find(g=>pointInPolygon([project.location.lng,project.location.lat],g.polygon));b.innerHTML=h?`<b>LEGEND</b><div class="map-legend-row"><span class="swatch" style="background:${h.color}"></span><span><strong>${esc(h.unitCode?.toUpperCase()||'')}</strong> ${esc(h.official?.title||h.name)}</span></div><small>${esc(h.description)}</small>`:`<b>LEGEND</b><div>${k==='surficial'?'OGS MRD128':'Bedrock geology'}</div><small>No site unit detected</small>`}
$('saveProject').onclick=save;$('newProject').onclick=()=>{if(confirm('Start a new local project?')){localStorage.removeItem(STORAGE);location.reload()}};$('exportJson').onclick=()=>dl(`${safe(project.name||'phase-i-project')}.json`,JSON.stringify(project,null,2),'application/json');$('importJson').onchange=async e=>{try{project=JSON.parse(await e.target.files[0].text());save();location.reload()}catch{alert('Invalid project JSON')}};$('exportDxf').onclick=()=>dl(`${safe(project.name||'phase-i')}.dxf`,buildDxf(project),'application/dxf');
$('printA3').onclick=()=>{if(!project.location)return alert('Locate property first.');zoom(active);renderGeo();refreshPrint();$('printMapHost').appendChild($('map'));printMoved=true;map.invalidateSize(false);setTimeout(()=>window.print(),800)};window.addEventListener('afterprint',()=>{if(printMoved){$('mapHome').appendChild($('map'));printMoved=false;setTimeout(()=>map.invalidateSize(false),50)}});function refreshPrint(){const f=project.figures[active];$('printProject').textContent=[project.name,project.address].filter(Boolean).join(' — ')||'—';$('printNo').textContent=project.projectNo||'—';$('printDate').textContent=project.date||'—';$('printFigure').textContent=active;$('printTitle').textContent=f?.title||'';$('printScale').textContent=`AS SHOWN • ${fmt(f?.extentMeters||0)} context`;const k=active==='D'?'surficial':active==='E'?'bedrock':null;$('printSource').textContent=k?(geoSource[k]||(k==='surficial'?'Ontario Geological Survey MRD128-REV':'Configured bedrock source')):'Base mapping / aerial source as shown'}
function dl(n,t,ty){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type:ty}));a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function safe(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,64)||'phase-i'}function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
sync();
