import { parseElevationText, dedupePoints, metresPerPixel, buildCsv, buildDxf } from './lib/core.mjs';

const TILE_W = 800, TILE_H = 600, OVERLAP = 48, CONCURRENCY = 2, MAX_PROC_W = 6500;
const $ = (id) => document.getElementById(id);
let st = { file: null, src: null, w: 0, h: 0, pw: 0, ph: 0, procScale: 1, points: [], selected: -1, busy: false };

async function checkHealth(){try{const r=await fetch('/api/health',{cache:'no-store'}),j=await r.json();$('health').textContent=j.ok?`Engine ready · ${j.engine}`:'Engine unavailable';$('health').className='pill '+(j.ok?'good':'warn')}catch{$('health').textContent='Engine unavailable';$('health').className='pill warn'}}
checkHealth();

$('file').onchange=e=>{st.file=e.target.files?.[0]||null;$('start').disabled=!st.file;$('status').textContent=st.file?`${st.file.name} · ${(st.file.size/1048576).toFixed(2)} MB`:'Choose a survey image.'};

async function decode(file){
  const lower=file.name.toLowerCase();
  if(lower.endsWith('.tif')||lower.endsWith('.tiff')||file.type==='image/tiff'){
    const buf=await file.arrayBuffer(); const ifds=UTIF.decode(buf); if(!ifds.length) throw Error('TIFF could not be decoded');
    UTIF.decodeImage(buf,ifds[0]); const rgba=UTIF.toRGBA8(ifds[0]); const w=ifds[0].width,h=ifds[0].height;
    const scale=Math.min(1,MAX_PROC_W/w),pw=Math.max(1,Math.round(w*scale)),ph=Math.max(1,Math.round(h*scale));
    const imageData=new ImageData(new Uint8ClampedArray(rgba.buffer,rgba.byteOffset,rgba.byteLength),w,h); const bmp=await createImageBitmap(imageData);
    const c=document.createElement('canvas');c.width=pw;c.height=ph;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,pw,ph);ctx.drawImage(bmp,0,0,w,h,0,0,pw,ph);bmp.close();return{canvas:c,origW:w,origH:h,scale};
  }
  const bmp=await createImageBitmap(file),w=bmp.width,h=bmp.height,scale=Math.min(1,MAX_PROC_W/w),pw=Math.round(w*scale),ph=Math.round(h*scale);const c=document.createElement('canvas');c.width=pw;c.height=ph;c.getContext('2d').drawImage(bmp,0,0,w,h,0,0,pw,ph);bmp.close();return{canvas:c,origW:w,origH:h,scale};
}
function tiles(w,h){const a=[],sx=TILE_W-OVERLAP,sy=TILE_H-OVERLAP;for(let y=0;y<h;y+=sy){for(let x=0;x<w;x+=sx){a.push({x,y,w:Math.min(TILE_W,w-x),h:Math.min(TILE_H,h-y)});if(x+TILE_W>=w)break}if(y+TILE_H>=h)break}return a}
function tileData(src,t){const c=document.createElement('canvas');c.width=t.w;c.height=t.h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.fillStyle='white';ctx.fillRect(0,0,t.w,t.h);ctx.drawImage(src,t.x,t.y,t.w,t.h,0,0,t.w,t.h);return{ctx,data:c.toDataURL('image/jpeg',.90)}}
async function spot(data){const r=await fetch('/api/spot',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({imageDataUrl:data})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Spotting failed');return j}
function grayAt(ctx,x,y){const d=ctx.getImageData(Math.max(0,x),Math.max(0,y),1,1).data;return .299*d[0]+.587*d[1]+.114*d[2]}
function findDot(ctx,poly,w,h){if(!poly||poly.length<4)return null;const mid=(a,b)=>({x:(a[0]+b[0])/2,y:(a[1]+b[1])/2}),a=mid(poly[0],poly[3]),b=mid(poly[1],poly[2]);let vx=b.x-a.x,vy=b.y-a.y;const L=Math.hypot(vx,vy)||1;vx/=L;vy/=L;let best=null;for(const s of[{p:a,dx:-vx,dy:-vy},{p:b,dx:vx,dy:vy}])for(let d=4;d<=28;d+=2){const cx=Math.round(s.p.x+s.dx*d),cy=Math.round(s.p.y+s.dy*d);if(cx<6||cy<6||cx>=w-6||cy>=h-6)continue;let inner=0,ring=0;for(let yy=-5;yy<=5;yy++)for(let xx=-5;xx<=5;xx++){const dark=grayAt(ctx,cx+xx,cy+yy)<100;if(dark){ring++;if(Math.abs(xx)<=2&&Math.abs(yy)<=2)inner++}}const score=inner*2-ring*.35-d*.03;if(inner>=5&&ring<=38&&(!best||score>best.score))best={x:cx,y:cy,score}}return best&&best.score>4?best:null}
function center(poly){return{x:poly.reduce((a,q)=>a+q[0],0)/poly.length,y:poly.reduce((a,q)=>a+q[1],0)/poly.length}}
function candidates(j,t,ctx){const out=[],texts=j.rec_texts||[],polys=j.rec_polys||[];for(let i=0;i<Math.min(texts.length,polys.length);i++){const parsed=parseElevationText(texts[i]);if(!parsed.length)continue;const poly=polys[i].map(q=>[Number(q[0]),Number(q[1])]),c=center(poly),dot=findDot(ctx,poly,t.w,t.h);parsed.forEach((p,k)=>{let lx=dot?dot.x:c.x,ly=dot?dot.y:c.y;if(parsed.length>1&&!dot){const a=poly[0],b=poly[1],f=(k+.5)/parsed.length;lx=a[0]+(b[0]-a[0])*f;ly=a[1]+(b[1]-a[1])*f}const valid=p.validRange;const likelyContour=p.roundHundredth&&!dot;out.push({value:valid?p.value:null,raw:p.raw,rawFull:String(texts[i]),x:(t.x+lx)/st.procScale,y:(t.y+ly)/st.procScale,status:(valid&&dot&&!likelyContour&&parsed.length===1)?'OK':'REVIEW',include:valid&&!likelyContour,confidence:valid&&dot?.92:valid?.62:.35})})}return out}
async function pool(items,worker,limit){let idx=0,done=0;async function one(){while(true){const i=idx++;if(i>=items.length)return;try{await worker(items[i],i)}catch(e){console.warn(e)}done++;$('bar').style.width=(done/items.length*100).toFixed(1)+'%';$('status').textContent=`Processing tile ${done} / ${items.length} · ${st.points.length} candidates`}}await Promise.all(Array.from({length:limit},one))}

$('start').onclick=async()=>{if(!st.file||st.busy)return;st.busy=true;$('start').disabled=true;$('csv').disabled=$('dxf').disabled=true;st.points=[];$('bar').style.width='0%';try{$('status').textContent='Decoding image…';const dec=await decode(st.file);st.src=dec.canvas;st.w=dec.origW;st.h=dec.origH;st.pw=dec.canvas.width;st.ph=dec.canvas.height;st.procScale=dec.scale;const pv=$('preview'),sc=Math.min(1,1800/st.pw);pv.width=Math.round(st.pw*sc);pv.height=Math.round(st.ph*sc);pv.getContext('2d').drawImage(st.src,0,0,pv.width,pv.height);$('work').classList.remove('hidden');const ts=tiles(st.pw,st.ph);await pool(ts,async(t)=>{const z=tileData(st.src,t),j=await spot(z.data);st.points=dedupePoints(st.points.concat(candidates(j,t,z.ctx)));renderTable();renderMarkers()},CONCURRENCY);$('bar').style.width='100%';renderTable();renderMarkers();updateExport();$('status').textContent=`DONE · ${st.points.length} numeric candidates · ${selected().length} included · ${ts.length} tiles · ${Math.round(st.procScale*100)}% OCR scale`}catch(e){$('status').textContent='ERROR: '+e.message;$('bar').style.width='0%'}finally{st.busy=false;$('start').disabled=!st.file}};

function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderTable(){const b=$('rows');b.innerHTML='';st.points.forEach((p,i)=>{const tr=document.createElement('tr');if(i===st.selected)tr.className='sel';tr.innerHTML=`<td><input data-use type="checkbox" ${p.include?'checked':''}></td><td>${i+1}</td><td><input data-val type="number" step=".01" value="${p.value??''}"></td><td><input data-x type="number" step="1" value="${Math.round(p.x)}"></td><td><input data-y type="number" step="1" value="${Math.round(p.y)}"></td><td>${escapeHtml(p.rawFull)}</td><td class="${p.status==='OK'?'oktxt':'revtxt'}">${p.status}</td><td><button data-del>×</button></td>`;tr.onclick=()=>{st.selected=i;renderTable();renderMarkers()};tr.querySelector('[data-use]').onchange=e=>{e.stopPropagation();p.include=e.target.checked;updateExport()};tr.querySelector('[data-val]').onchange=e=>{p.value=Number(e.target.value);p.status='REVIEW';updateExport()};tr.querySelector('[data-x]').onchange=e=>{p.x=Number(e.target.value);renderMarkers()};tr.querySelector('[data-y]').onchange=e=>{p.y=Number(e.target.value);renderMarkers()};tr.querySelector('[data-del]').onclick=e=>{e.stopPropagation();st.points.splice(i,1);renderTable();renderMarkers();updateExport()};b.appendChild(tr)});$('count').textContent=st.points.length+' candidates'}
function renderMarkers(){const host=$('markers'),pv=$('preview'),stage=$('stage');host.innerHTML='';const r=pv.getBoundingClientRect(),sr=stage.getBoundingClientRect();host.style.position='absolute';host.style.left=(r.left-sr.left+stage.scrollLeft)+'px';host.style.top=(r.top-sr.top+stage.scrollTop)+'px';host.style.width=r.width+'px';host.style.height=r.height+'px';st.points.forEach((p,i)=>{const m=document.createElement('div');m.className='marker '+(p.status==='OK'?'':'review')+(i===st.selected?' selected':'');m.style.left=(p.x/st.w*100)+'%';m.style.top=(p.y/st.h*100)+'%';m.title=`${p.value??p.raw} · ${p.status}`;m.onclick=e=>{e.stopPropagation();st.selected=i;renderTable();renderMarkers()};host.appendChild(m)})}
window.addEventListener('resize',renderMarkers);$('stage').onclick=e=>{if(st.selected<0||!st.w)return;const r=$('preview').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;const p=st.points[st.selected];p.x=(e.clientX-r.left)/r.width*st.w;p.y=(e.clientY-r.top)/r.height*st.h;p.status='REVIEW';renderTable();renderMarkers()};$('add').onclick=()=>{if(!st.w)return;st.points.push({value:null,raw:'manual',rawFull:'manual',x:st.w/2,y:st.h/2,status:'REVIEW',include:false,confidence:1});st.selected=st.points.length-1;renderTable();renderMarkers()};
function opts(){return{imageHeight:st.h,scale:Number($('scale').value),dpi:Number($('dpi').value),originX:Number($('originX').value||0),originY:Number($('originY').value||0)}}function selected(){return st.points.filter(p=>p.include&&Number.isFinite(p.value))}function updateMpp(){$('mpp').textContent=`Scale conversion: ${metresPerPixel($('scale').value,$('dpi').value).toFixed(6)} m/pixel`}$('scale').oninput=$('dpi').oninput=updateMpp;updateMpp();function updateExport(){const n=selected().length;$('csv').disabled=$('dxf').disabled=n===0;$('exportNote').textContent=n?`${n} points will be exported.`:'No included valid points yet.'}function dl(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)}$('csv').onclick=()=>{if(!selected().length)return;dl((st.file?.name||'survey').replace(/\.[^.]+$/,'')+'_spots.csv',buildCsv(st.points,opts()),'text/csv')};$('dxf').onclick=()=>{if(!selected().length)return;dl((st.file?.name||'survey').replace(/\.[^.]+$/,'')+'_spots.dxf',buildDxf(st.points,opts()),'application/dxf')};
